version: '3.8'

services:
  radicale:
    read_only: true
    env_file:
    - .env
    environment:
    - GIT_AUTHOR_EMAIL=$GIT_EMAIL
    - GIT_AUTHOR_NAME=$GIT_USERNAME
    ports:
    - "8000:8000"
    volumes:
    # needed for ssh authentication with pub/private key
    - .ssh:/var/radicale/.ssh
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)

volumes:
  radicale:
