[project]
name = "docker-radicale"
version = "0.1.0"
description = "docker-radicale (Python support scripts for this repository)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]
